### ISSUE TITLE
U. Minnesota flagged as a recipient of funds for a Wisconsin distrct

### ISSUE THREAD

**Issue by bnord** [mbaumer/us_hep_funding#13]
For sensenbrenner:
https://mbaumer.github.io/us_hep_funding/states/WI/

In the past 6 years, this district has received: $2,479,000.00 in SC HEP grants.
                              Amount ($)
Institution             Year            
University of Minnesota 2015     2479000

**Comment by mbaumer** [comment]
Sorry! This was a typo by the DOE in the raw data: the state was MN, but the district was WI-05 instead of MN-05. Now fixed.
